#include "parser.hxx"

static void EvalToken()
{
	switch(ParserState.Token.type)
	{
		case(37):
		{
			scope* ts = currentScope;
			while(ts->isIndentBased && ts != nullptr)
			{
				//,
				//, close ts
				//,
				if(!EntityManagement::close(ts);)
					ts = ts->parent;
			}
			if(ts != nullptr)
			{
				//,
				//, close ts
				//,
				endBody(ts);
				//,
				//, ts is now the new scope
				//,
				updateCurrentScope(ts);
			}
			else
			{
				std::cerr << "there are no curly-brace based bodies to close!";
			}
			break;
		}
		case(14):
			parse::Descriptor();
			break;
		case(5):
			parse::Directive();
			break;
		case(26):
		case(25):
		case(22):
		case(21):
		case(20):
		case(30):
			parse::AttributeList();
			EvalToken();
			break;
		case(8):
			parse::Keyword();
			break;
		case(9):
			parse::Declaration::FunctionOrVariable();
			break;
		case(10):
		case(11):
			parse::Expression();
			break;
		case(1):
			parse::NewUnique();
			break;
		default:
			compilerBug("parser defaulted on first token switch.",originCoreHere,source(),"");
	}
}

void parse::Line()
{
	unimplementedDebugInfo("debug line information");
	if ((L.leadingSpaces < currentScope->leadingSpace) && currentScope->isIndentBased && L.file != "code generated by compiler") 
	{
		scope* ts = currentScope;
		while (true) {
			if (L.leadingSpaces < ts->leadingSpace && ts->isIndentBased) {
				if(endBody(ts))break;
			} else {
				break;
			}
			if (ts == nullptr) {
				std::cout << "indentation error! (2)" << std::endl;
				break;
			}
		}
		updateCurrentScope(ts);
	}
	ParserState.Token = ParserState.Line.nextToken();
	EvalToken();
}
